version: '3.8'

services:
  # Streamlit Application
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8080"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET_KEY=dev-secret-key-change-in-production
      - API_BASE_URL=http://localhost:3000
    depends_on:
      - redis
    volumes:
      - ./app:/app
    networks:
      - investforge-network

  # Redis for session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - investforge-network

  # Landing page (Nginx for local development)
  landing:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./landing:/usr/share/nginx/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - investforge-network

  # API (for local development using serverless-offline)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - dynamodb
      - redis
    volumes:
      - ./api:/app
    networks:
      - investforge-network

  # DynamoDB Local for development
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - investforge-network

volumes:
  redis_data:

networks:
  investforge-network:
    driver: bridge