[server]
port = 8080
address = "0.0.0.0"
baseUrlPath = "/app"
enableStaticServing = true
enableCORS = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"