AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFront distribution for InvestForge unified architecture'

Parameters:
  DomainName:
    Type: String
    Default: investforge.io
    Description: Domain name for the application
  CertificateArn:
    Type: String
    Description: ARN of the existing ACM SSL certificate
  ALBDomainName:
    Type: String
    Description: DNS name of the existing Application Load Balancer
  Route53HostedZoneId:
    Type: String
    Description: Route 53 hosted zone ID for the domain

Resources:
  # S3 bucket for landing page
  LandingPageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DomainName}-cloudfront-landing"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  # CloudFront Origin Access Control
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${DomainName}-OAC"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # S3 bucket policy for CloudFront access
  LandingPageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LandingPageBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${LandingPageBucket}/*"
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  # CloudFront distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          # S3 origin for landing page
          - Id: S3Origin
            DomainName: !GetAtt LandingPageBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref OriginAccessControl
          # ALB origin for app and API
          - Id: ALBOrigin
            DomainName: !Ref ALBDomainName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
              OriginKeepaliveTimeout: 5
              OriginReadTimeout: 30
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
        CacheBehaviors:
          # App traffic to ALB (Streamlit)
          - PathPattern: "/app*"
            TargetOriginId: ALBOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: true
              Headers:
                - Authorization
                - Content-Type
                - Host
                - Origin
                - Referer
                - User-Agent
                - X-Forwarded-For
                - X-Forwarded-Proto
                - X-Forwarded-Port
              Cookies:
                Forward: all
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
          # API traffic to ALB (Lambda functions)
          - PathPattern: "/api*"
            TargetOriginId: ALBOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: true
              Headers:
                - Authorization
                - Content-Type
                - Host
                - Origin
                - Referer
                - User-Agent
                - X-Forwarded-For
                - X-Forwarded-Proto
                - X-Forwarded-Port
              Cookies:
                Forward: all
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300

  # Route 53 record updates
  Route53RecordRoot:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
        EvaluateTargetHealth: false

Outputs:
  CloudFrontDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontDomain"

  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}-CloudFrontId"

  LandingPageBucketName:
    Description: S3 bucket for landing page
    Value: !Ref LandingPageBucket
    Export:
      Name: !Sub "${AWS::StackName}-LandingBucket"

  CloudFrontURL:
    Description: CloudFront URL
    Value: !Sub "https://${DomainName}"
    Export:
      Name: !Sub "${AWS::StackName}-URL"

  ArchitectureStatus:
    Description: Architecture implementation status
    Value: !Sub |
      ✅ CloudFront Distribution: Created
      ✅ S3 Landing Page: ${LandingPageBucket}
      ✅ ALB Integration: /app/* and /api/* → ${ALBDomainName}
      ✅ Route 53: ${DomainName} → CloudFront
      🎯 Architecture: COMPLETE