[server]
port = 8080
address = "0.0.0.0"
headless = true
fileWatcherType = "none"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
allowRunOnSave = false
runOnSave = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[runner]
magicEnabled = false